# Generated by Django 4.2.7 on 2025-04-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_cards', '0003_alter_healthcard_options_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at', 'user__email'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='card',
            field=models.ForeignKey(help_text='The health card this vote is for.', on_delete=django.db.models.deletion.CASCADE, related_name='card_votes', to='health_cards.healthcard'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment provided by the user.', null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment_summary',
            field=models.TextField(blank=True, help_text='(Beta) AI-generated summary of the comment.', null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the vote was initially created.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the vote.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(help_text='The health check session this vote belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='session_votes', to='health_cards.healthchecksession'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], help_text='The trend perceived by the user.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the vote was last updated.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(help_text='The user who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_value',
            field=models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], help_text='The traffic light value selected by the user.', max_length=10),
        ),
    ]
