# Generated by Django 4.2.7 on 2025-04-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_cards', '0003_alter_healthcard_options_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='departmentsummary',
            options={'ordering': ['-session__year', '-session__quarter', 'department__name', 'card__title'], 'verbose_name': 'Department Summary', 'verbose_name_plural': 'Department Summaries'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['department__name', 'name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(blank=True, help_text='The Department Manager directly managing this department.', limit_choices_to={'role': 'department_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directly_managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the department was created.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the department.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Name of the department.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='senior_manager',
            field=models.ForeignKey(blank=True, help_text='The Senior Manager responsible for overseeing this department.', limit_choices_to={'role': 'senior_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='amber_count',
            field=models.IntegerField(default=0, help_text="Number of 'Amber' votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='card',
            field=models.ForeignKey(help_text='The health card this summary relates to.', on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthcard'),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the summary record was created.'),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='declining_count',
            field=models.IntegerField(default=0, help_text="Number of 'Declining' trend votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='department',
            field=models.ForeignKey(help_text='The department this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='department_summaries', to='teams.department'),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='green_count',
            field=models.IntegerField(default=0, help_text="Number of 'Green' votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the department summary record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='improving_count',
            field=models.IntegerField(default=0, help_text="Number of 'Improving' trend votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='red_count',
            field=models.IntegerField(default=0, help_text="Number of 'Red' votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='session',
            field=models.ForeignKey(help_text='The health check session this summary is for.', on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthchecksession'),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='stable_count',
            field=models.IntegerField(default=0, help_text="Number of 'Stable' trend votes."),
        ),
        migrations.AlterField(
            model_name='departmentsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the summary record was last updated.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the team was created.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(help_text='The department this team belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.department'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the team.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='The Team Leader responsible for this team.', limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'department')},
        ),
    ]
