# Generated by Django 5.1.7 on 2025-03-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_cards', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthchecksession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='healthchecksession',
            unique_together={('team', 'quarter', 'year')},
        ),
    ]
