# Generated by Django 4.2.7 on 2025-05-01 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('health_cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthchecksession',
            options={'ordering': ['-session_date']},
        ),
        migrations.AlterUniqueTogether(
            name='healthchecksession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='healthcard',
            name='example_awesome',
        ),
        migrations.RemoveField(
            model_name='healthcard',
            name='example_crappy',
        ),
        migrations.AddField(
            model_name='healthcard',
            name='example_amber',
            field=models.TextField(default='.', help_text='Example of amber status'),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='example_green',
            field=models.TextField(default='', help_text='Example of green status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcard',
            name='example_red',
            field=models.TextField(default='', help_text='Example of red status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcard',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to the card image relative to static files', max_length=255),
        ),
        migrations.AddField(
            model_name='healthchecksession',
            name='name',
            field=models.CharField(default='', help_text='Session name, e.g., Q1 2024', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthchecksession',
            name='session_date',
            field=models.DateField(default=datetime.date(2025, 5, 1), help_text='Date the session represents or was held'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='healthchecksession',
            unique_together={('team', 'name')},
        ),
        migrations.RemoveField(
            model_name='healthchecksession',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='healthchecksession',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='healthchecksession',
            name='year',
        ),
    ]
