# Generated by Django 4.2.7 on 2025-05-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_cards', '0003_alter_healthchecksession_options_and_more'),
        ('teams', '0001_initial'),
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votesummary',
            options={'ordering': ['-session__session_date']},
        ),
        migrations.AlterUniqueTogether(
            name='votesummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='votesummary',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthchecksession'),
        ),
        migrations.AlterUniqueTogether(
            name='votesummary',
            unique_together={('team', 'card', 'session')},
        ),
        migrations.RemoveField(
            model_name='votesummary',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='votesummary',
            name='year',
        ),
    ]
