# Generated by Django 4.2.7 on 2025-04-30 12:40

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Used for login.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('team_leader', 'Team Leader'), ('senior_manager', 'Senior Manager'), ('department_manager', 'Department Manager'), ('admin', 'Administrator')], default='engineer', help_text='User role determining permissions.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, help_text='The team this user belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
