# Generated by Django 4.2.7 on 2025-04-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('health_cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcard',
            options={'ordering': ['title'], 'verbose_name': 'Health Card', 'verbose_name_plural': 'Health Cards'},
        ),
        migrations.AlterModelOptions(
            name='healthchecksession',
            options={'ordering': ['-year', '-quarter', 'team__name'], 'verbose_name': 'Health Check Session', 'verbose_name_plural': 'Health Check Sessions'},
        ),
        migrations.AddField(
            model_name='healthcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this card is currently active and available for sessions.'),
        ),
        migrations.AddField(
            model_name='healthchecksession',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the session was closed.', null=True),
        ),
        migrations.AddField(
            model_name='healthchecksession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this session (typically Team Leader or Admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the health card was created.'),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='description',
            field=models.TextField(help_text='Detailed description of the health card topic.'),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='example_awesome',
            field=models.TextField(help_text='Example illustrating a positive state (Green).', verbose_name='Awesome Example'),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='example_crappy',
            field=models.TextField(help_text='Example illustrating a negative state (Red).', verbose_name='Crappy Example'),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the health card.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='title',
            field=models.CharField(help_text='Concise title for the health card topic.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='cards',
            field=models.ManyToManyField(help_text='Health cards included in this session.', limit_choices_to={'is_active': True}, related_name='health_check_sessions', to='health_cards.healthcard'),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the session was created.'),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the health check session.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], help_text='The quarter this session belongs to.', max_length=2),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Current status of the session (Open/Closed).', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='team',
            field=models.ForeignKey(help_text='The team participating in this session.', on_delete=django.db.models.deletion.CASCADE, related_name='health_check_sessions', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='healthchecksession',
            name='year',
            field=models.IntegerField(default=2025, help_text='The year this session belongs to.'),
        ),
    ]
