# Generated by Django 4.2.7 on 2025-04-30 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health_cards', '0003_alter_healthcard_options_and_more'),
        ('teams', '0002_alter_department_options_and_more'),
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsummary',
            options={'ordering': ['-session__year', '-session__quarter', 'team__name', 'card__title'], 'verbose_name': 'Team Summary', 'verbose_name_plural': 'Team Summaries'},
        ),
        migrations.AlterModelOptions(
            name='votesummary',
            options={'ordering': ['-year', '-quarter', 'team__name', 'card__title'], 'verbose_name': 'Vote Summary (Historical)', 'verbose_name_plural': 'Vote Summaries (Historical)'},
        ),
        migrations.RemoveField(
            model_name='teamsummary',
            name='comments_summary',
        ),
        migrations.RemoveField(
            model_name='votesummary',
            name='trend',
        ),
        migrations.AddField(
            model_name='teamsummary',
            name='aggregated_comments_summary',
            field=models.TextField(blank=True, help_text='(Beta) AI-generated summary of all comments for this card in this session.', null=True, verbose_name='Aggregated Comments Summary (Beta)'),
        ),
        migrations.AddField(
            model_name='votesummary',
            name='aggregated_trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', help_text='Overall calculated trend for this card in this period.', max_length=10, verbose_name='Aggregated Trend'),
        ),
        migrations.AddField(
            model_name='votesummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the historical summary record was last updated.'),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='amber_count',
            field=models.IntegerField(default=0, help_text="Number of 'Amber' votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='card',
            field=models.ForeignKey(help_text='The health card this summary relates to.', on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthcard'),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the summary record was created.'),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='declining_count',
            field=models.IntegerField(default=0, help_text="Number of 'Declining' trend votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='green_count',
            field=models.IntegerField(default=0, help_text="Number of 'Green' votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the team summary record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='improving_count',
            field=models.IntegerField(default=0, help_text="Number of 'Improving' trend votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='red_count',
            field=models.IntegerField(default=0, help_text="Number of 'Red' votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='session',
            field=models.ForeignKey(help_text='The health check session this summary is for.', on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthchecksession'),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='stable_count',
            field=models.IntegerField(default=0, help_text="Number of 'Stable' trend votes."),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='team',
            field=models.ForeignKey(help_text='The team this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='teamsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the summary record was last updated (e.g., when votes are added/changed).'),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='amber_percentage',
            field=models.FloatField(default=0, help_text="Percentage of 'Amber' votes."),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='card',
            field=models.ForeignKey(help_text='The health card this historical summary relates to.', on_delete=django.db.models.deletion.CASCADE, to='health_cards.healthcard'),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the historical summary record was created.'),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='green_percentage',
            field=models.FloatField(default=0, help_text="Percentage of 'Green' votes."),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the vote summary record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], help_text='The quarter this summary represents.', max_length=2),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='red_percentage',
            field=models.FloatField(default=0, help_text="Percentage of 'Red' votes."),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='team',
            field=models.ForeignKey(help_text='The team this historical summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='vote_history', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='year',
            field=models.IntegerField(help_text='The year this summary represents.'),
        ),
    ]
